time:
  dt_cfd: 0.00005
  t_end: 1.92

normal: [0.5021663407735754, -0.517868213597601, 0.6925615348395455]

boundary:
  - {id: 4, name: inlet,  profile_space: uniform, profile_time: wave,    dir: 0, value: 1}
  - {id: 4, name: inlet,  profile_space: uniform, profile_time: wave,    dir: 1, value: 1}
  - {id: 4, name: inlet,  profile_space: uniform, profile_time: wave,    dir: 2, value: 1}
  - {id: 6, name: wall,   profile_space: uniform, profile_time: uniform, dir: 0, value: 0}
  - {id: 6, name: wall,   profile_space: uniform, profile_time: uniform, dir: 1, value: 0}
  - {id: 6, name: wall,   profile_space: uniform, profile_time: uniform, dir: 2, value: 0}